// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Remailer is an autogenerated mock type for the Remailer type
type Remailer struct {
	mock.Mock
}

// StartRemailer provides a mock function with given fields:
func (_m *Remailer) StartRemailer() {
	_m.Called()
}

type mockConstructorTestingTNewRemailer interface {
	mock.TestingT
	Cleanup(func())
}

// NewRemailer creates a new instance of Remailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRemailer(t mockConstructorTestingTNewRemailer) *Remailer {
	mock := &Remailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
